### ISSUE TITLE
Broken link in Installation section of README

### ISSUE THREAD

**Issue by mikeapted** [cdklabs/aws-delivlib#1061]
Last line in the Installation section links to:

https://github.com/cdklabs/aws-delivlib/blob/main/pipeline/delivlib.ts

which is a 404 now.

**Comment by pizzaz93** [comment]
There's a devlib pipeline in a test file with a similar syntax, would that be a good replacement? https://github.com/cdklabs/aws-delivlib/blob/8b6eac1947b73ca546810e8a66bb493be98f60bd/lib/__tests__/test-stack.ts#L33
