### ISSUE TITLE
Build Image for Maven Release no longer available

### ISSUE THREAD

**Issue by biffgaut** [cdklabs/aws-delivlib#1114]
The CDK team reorganized the jsii/superchain images recently (on 5/6/22 I believe) and discontinued the "latest" tag. The pipeline step created by [PublishToMavenProject](https://github.com/cdklabs/aws-delivlib/blob/b252f0156aff3362740c1889a9386a2e88da53d3/lib/publishing.ts#L76) now fails.

Error message received when the Publish to Maven task is executed is:

> BUILD_CONTAINER_UNABLE_TO_PULL_IMAGE: Unable to pull customer's container image. CannotPullContainerError: Error response from daemon: manifest for jsii/superchain:latest not found: manifest unknown: manifest unknown

**Comment by biffgaut** [comment]
The same issue affects the MergeBack pipeline step - I'm guessing it probably occurs other places as well...

**Comment by biffgaut** [comment]
Docs that describe the discontinuation of the latest tag - https://hub.docker.com/r/jsii/superchain

**Comment by CamdenFoucht** [comment]
Facing the same error when running `autoBump` on our pipeline

**Comment by biffgaut** [comment]
Any comment on this issue? While I'm not familiar with the internals of the library, it appears that [this line](https://github.com/cdklabs/aws-delivlib/blob/4a2c8e8f1396305b1b531ed6f3a22677cb2cd432/lib/build-env.ts#L17) requires updating since the latest tag has been discontinued.

While it appears we can change our code to send an image to PublishToMavenProject, that doesn't seem to be possible with AutoMergeBack.
