### ISSUE TITLE
Consistent parameters

### ISSUE THREAD

**Issue by rhboyd** [cdklabs/aws-delivlib#147]
npm/pypi/etc... expect tokens to be in SecretsManager but the Github source expects the OAuth token to be in SSM Parameter Store. The SSM Parameter also expects regular strings and not SecureStrings, which makes me very sad.

The tokens should be in a consistent location and the value of the expected `key` should be documented.

<3

**Comment by richardhboyd** [comment]
plz no close

**Comment by richardhboyd** [comment]
WTF Github bot?!?!?

**Comment by richardhboyd** [comment]
Github-actions bot, I will fight you!!
