### ISSUE TITLE
delivlib should publish to AWS CodeArtifact (npm & pypi)

### ISSUE THREAD

**Issue by ahammond** [cdklabs/aws-delivlib#371]
We would like to publish our private CDK packages in AWS CodeArtifact. We current use ts and would like to add python support.

**Comment by ahammond** [comment]
https://docs.aws.amazon.com/codeartifact/latest/ug/using-npm.html and https://docs.aws.amazon.com/codeartifact/latest/ug/using-python.html

**Comment by NetaNir** [comment]
We couldn't agree more :) marking this as a feature request.

**Comment by nbaillie** [comment]
@NetaNir , Could TWINE_REPOSITORY_URL be an optional addition to the secret-manager secret and read the CodeArtifact url from there in pypi/publish.sh?

**Comment by RomainMuller** [comment]
That sure sounds like a thing that could be done. Pull requests are always welcome 🙃
